# title_tag_text: X-MAS in Schlumpfhausen
title_tag_text: Schlumpffest  
h1_tag_text: Schlumpfiges für Jenny von Benny *

exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]
